### PR TITLE
Creating fix for dynamic reconfigure bug

### PR DESCRIPTION
**Pull request by fulkast**
In catkin build system the correct command in the python dynamic reconfigure script should be:
"from dynamic_reconfigure.parameter_generator_**catkin** import *"

### CODE REVIEW

**Comment by fulkast** [comment]
Hi Kevin,
May you please give this PR a try on your local system and confirm if it frees us from the necessity of running the 3 copy commands that you currently have in the wiki?

Cheers,
Frank

**Comment by bespoke-code** [comment]
Hello Frank,

Have you tested this on your system? I would gladly try this out tomorrow - I'd be very happy if it simplifies the build process since running extra commands is not always the preffered way to go for me. 

I will post my results. I hope for a positive outcome!

All the best,
Andrej

**Comment by fulkast** [comment]
Hello Andrej,

Yes, I did try it. As a matter of fact, I ran `$ catkin_make` on a clean catkin_ws to make sure that the config headers weren't already previously built by another command.

Still, it would be great if someone else could verify that this also works for them.

Cheers,
Frank

**Comment by bespoke-code** [comment]
Hello Frank,

I can indeed confirm that this addition removes the need of running extra commands as originally presented in the Wiki. 
Built LSD_SLAM successfully in a clean workspace on Ubuntu 16.04.3 LTS x64 GNOME with only 1 `catkin_make` command. Awesome! 👍

**Comment by kevin-george** [comment]
Thank you for the fix @fulkast  and thank you for testing that @bespoke-code!
I'll update the wiki accordingly :)

Merging fix.

**Pull request merged**
